[{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2769",
	"severity": 8,
	"message": "没有与此调用匹配的重载。\n  第 1 个重载(共 2 个)，“(def: () => { 描述: string; 数量: unknown; }): ZodPrefault<ZodObject<{ 描述: ZodString; 数量: ZodCoercedNumber<unknown>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“() => { 描述: string; 数量: unknown; }”的参数。\n      类型“{}”提供的内容与签名“(): { 描述: string; 数量: unknown; }”不匹配。\n  第 2 个重载(共 2 个)，“(def: { 描述: string; 数量: unknown; }): ZodPrefault<ZodObject<{ 描述: ZodString; 数量: ZodCoercedNumber<unknown>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“{ 描述: string; 数量: unknown; }”的参数。\n      类型“{}”缺少类型“{ 描述: string; 数量: unknown; }”中的以下属性: 描述, 数量",
	"source": "ts",
	"startLineNumber": 120,
	"startColumn": 21,
	"endLineNumber": 120,
	"endColumn": 23,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2349",
	"severity": 8,
	"message": "此表达式不可调用。\n  类型 \"{ 对<user>(): z.string; }\" 没有调用签名。",
	"source": "ts",
	"startLineNumber": 182,
	"startColumn": 21,
	"endLineNumber": 183,
	"endColumn": 26,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "eslint1",
	"severity": 8,
	"message": "Parsing error: '(' expected.",
	"source": "eslint",
	"startLineNumber": 183,
	"startColumn": 15,
	"endLineNumber": 183,
	"endColumn": 15,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“(”。",
	"source": "ts",
	"startLineNumber": 183,
	"startColumn": 16,
	"endLineNumber": 183,
	"endColumn": 17,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2749",
	"severity": 8,
	"message": "“z.string”表示值，但在此处用作类型。是否指“类型 z.string”?",
	"source": "ts",
	"startLineNumber": 183,
	"startColumn": 18,
	"endLineNumber": 183,
	"endColumn": 26,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“{”。",
	"source": "ts",
	"startLineNumber": 183,
	"startColumn": 26,
	"endLineNumber": 183,
	"endColumn": 27,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "找不到名称“对成秀敏”。",
	"source": "ts",
	"startLineNumber": 184,
	"startColumn": 9,
	"endLineNumber": 184,
	"endColumn": 13,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“,”。",
	"source": "ts",
	"startLineNumber": 184,
	"startColumn": 13,
	"endLineNumber": 184,
	"endColumn": 14,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "应有 0-2 个参数，但获得 3 个。",
	"source": "ts",
	"startLineNumber": 184,
	"startColumn": 15,
	"endLineNumber": 184,
	"endColumn": 40,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1135",
	"severity": 8,
	"message": "应为参数表达式。",
	"source": "ts",
	"startLineNumber": 185,
	"startColumn": 7,
	"endLineNumber": 185,
	"endColumn": 8,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2769",
	"severity": 8,
	"message": "没有与此调用匹配的重载。\n  第 1 个重载(共 2 个)，“(def: () => { 关系值: any; 个人表现分?: unknown; }): ZodPrefault<ZodObject<{ 个人表现分: ZodPrefault<ZodPipe<ZodCoercedNumber<unknown>, ZodTransform<number, number>>>; 关系值: ZodObject<...>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“() => { 关系值: any; 个人表现分?: unknown; }”的参数。\n      类型“{}”提供的内容与签名“(): { 关系值: any; 个人表现分?: unknown; }”不匹配。\n  第 2 个重载(共 2 个)，“(def: { 关系值: any; 个人表现分?: unknown; }): ZodPrefault<ZodObject<{ 个人表现分: ZodPrefault<ZodPipe<ZodCoercedNumber<unknown>, ZodTransform<number, number>>>; 关系值: ZodObject<...>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“{ 关系值: any; 个人表现分?: unknown; }”的参数。\n      类型 \"{}\" 中缺少属性 \"关系值\"，但类型 \"{ 关系值: any; 个人表现分?: unknown; }\" 中需要该属性。",
	"source": "ts",
	"startLineNumber": 185,
	"startColumn": 19,
	"endLineNumber": 185,
	"endColumn": 21,
	"relatedInformation": [
		{
			"startLineNumber": 182,
			"startColumn": 7,
			"endLineNumber": 184,
			"endColumn": 41,
			"message": "在此处声明了 \"关系值\"。",
			"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts"
		}
	],
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2349",
	"severity": 8,
	"message": "此表达式不可调用。\n  类型 \"{ 对<user>(): z.string; }\" 没有调用签名。",
	"source": "ts",
	"startLineNumber": 193,
	"startColumn": 21,
	"endLineNumber": 194,
	"endColumn": 26,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“(”。",
	"source": "ts",
	"startLineNumber": 194,
	"startColumn": 16,
	"endLineNumber": 194,
	"endColumn": 17,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2749",
	"severity": 8,
	"message": "“z.string”表示值，但在此处用作类型。是否指“类型 z.string”?",
	"source": "ts",
	"startLineNumber": 194,
	"startColumn": 18,
	"endLineNumber": 194,
	"endColumn": 26,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“{”。",
	"source": "ts",
	"startLineNumber": 194,
	"startColumn": 26,
	"endLineNumber": 194,
	"endColumn": 27,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "找不到名称“对成秀敏”。",
	"source": "ts",
	"startLineNumber": 195,
	"startColumn": 9,
	"endLineNumber": 195,
	"endColumn": 13,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“,”。",
	"source": "ts",
	"startLineNumber": 195,
	"startColumn": 13,
	"endLineNumber": 195,
	"endColumn": 14,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "应有 0-2 个参数，但获得 3 个。",
	"source": "ts",
	"startLineNumber": 195,
	"startColumn": 15,
	"endLineNumber": 195,
	"endColumn": 42,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1135",
	"severity": 8,
	"message": "应为参数表达式。",
	"source": "ts",
	"startLineNumber": 196,
	"startColumn": 7,
	"endLineNumber": 196,
	"endColumn": 8,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2769",
	"severity": 8,
	"message": "没有与此调用匹配的重载。\n  第 1 个重载(共 2 个)，“(def: () => { 关系值: any; 个人表现分?: unknown; }): ZodPrefault<ZodObject<{ 个人表现分: ZodPrefault<ZodPipe<ZodCoercedNumber<unknown>, ZodTransform<number, number>>>; 关系值: ZodObject<...>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“() => { 关系值: any; 个人表现分?: unknown; }”的参数。\n      类型“{}”提供的内容与签名“(): { 关系值: any; 个人表现分?: unknown; }”不匹配。\n  第 2 个重载(共 2 个)，“(def: { 关系值: any; 个人表现分?: unknown; }): ZodPrefault<ZodObject<{ 个人表现分: ZodPrefault<ZodPipe<ZodCoercedNumber<unknown>, ZodTransform<number, number>>>; 关系值: ZodObject<...>; }, $strip>>”，出现以下错误。\n    类型“{}”的参数不能赋给类型“{ 关系值: any; 个人表现分?: unknown; }”的参数。\n      类型 \"{}\" 中缺少属性 \"关系值\"，但类型 \"{ 关系值: any; 个人表现分?: unknown; }\" 中需要该属性。",
	"source": "ts",
	"startLineNumber": 196,
	"startColumn": 19,
	"endLineNumber": 196,
	"endColumn": 21,
	"relatedInformation": [
		{
			"startLineNumber": 193,
			"startColumn": 7,
			"endLineNumber": 195,
			"endColumn": 43,
			"message": "在此处声明了 \"关系值\"。",
			"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts"
		}
	],
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2749",
	"severity": 8,
	"message": "“z.object”表示值，但在此处用作类型。是否指“类型 z.object”?",
	"source": "ts",
	"startLineNumber": 202,
	"startColumn": 10,
	"endLineNumber": 202,
	"endColumn": 18,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1005",
	"severity": 8,
	"message": "应为“,”。",
	"source": "ts",
	"startLineNumber": 202,
	"startColumn": 18,
	"endLineNumber": 202,
	"endColumn": 19,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "类型“{ 关系: ZodPrefault<ZodString>; 介入状态: ZodPrefault<ZodBoolean>; }”上不存在属性“prefault”。",
	"source": "ts",
	"startLineNumber": 205,
	"startColumn": 8,
	"endLineNumber": 205,
	"endColumn": 16,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "应为表达式。",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 3,
	"endLineNumber": 206,
	"endColumn": 4,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "应为声明或语句。",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 4,
	"endLineNumber": 206,
	"endColumn": 5,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "应为声明或语句。",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 5,
	"endLineNumber": 206,
	"endColumn": 6,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "2304",
	"severity": 8,
	"message": "找不到名称“prefault”。",
	"source": "ts",
	"startLineNumber": 206,
	"startColumn": 6,
	"endLineNumber": 206,
	"endColumn": 14,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1109",
	"severity": 8,
	"message": "应为表达式。",
	"source": "ts",
	"startLineNumber": 207,
	"startColumn": 1,
	"endLineNumber": 207,
	"endColumn": 2,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "1128",
	"severity": 8,
	"message": "应为声明或语句。",
	"source": "ts",
	"startLineNumber": 207,
	"startColumn": 2,
	"endLineNumber": 207,
	"endColumn": 3,
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "6133",
	"severity": 4,
	"message": "已声明“user”，但从未读取其值。",
	"source": "ts",
	"startLineNumber": 183,
	"startColumn": 10,
	"endLineNumber": 183,
	"endColumn": 16,
	"tags": [
		1
	],
	"modelVersionId": 6
},{
	"resource": "/Users/liuzixi/Desktop/tavern_helper_template/src/成秀敏/脚本/变量结构/index.ts",
	"owner": "typescript",
	"code": "6133",
	"severity": 4,
	"message": "已声明“user”，但从未读取其值。",
	"source": "ts",
	"startLineNumber": 194,
	"startColumn": 10,
	"endLineNumber": 194,
	"endColumn": 16,
	"tags": [
		1
	],
	"modelVersionId": 6
}]
